apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-net-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.podName }}
    spec:
      containers:
        - name: {{ .Values.podName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080