apiVersion: v1
kind: Service
metadata:
  name: asp-net-service
spec:
  type: NodePort
  selector:
    app: asp-net-pod
  ports:
    port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    targetPort: {{ .Values.service.targetPort }}
