apiVersion: v1
kind: Service
metadata:
  name: asp-net-service
spec:
  type: LoadBalancer
  selector:
    app: asp-net-pod
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
