replicaCount: 2

image:
  repository: "654654428802.dkr.ecr.us-east-1.amazonaws.com/asp.net.repo"
  tag: v3.0.0
  pullPolicy: IfNotPresent

service:
  port: 80
  type: NodePort
  targetPort: 8080
  name: asp-net-service
